import UIKit
import Capacitor

/// The app's Capacitor bridge view controller, subclassed for ONE reason:
/// registering TripGuardPlugin.
///
/// Capacitor does NOT discover plugins by scanning the runtime for
/// CAPBridgedPlugin conformers. `CapacitorBridge.registerPlugins()` reads
/// `capacitor.config.json`'s `packageClassList` and calls NSClassFromString
/// on each entry, and that list is generated by `npx cap sync` from the
/// npm-installed plugin packages only. TripGuardPlugin lives in this app
/// target, not in an npm package, so it would never appear there, and
/// hand-editing that file is pointless because every `cap sync` (which the
/// iOS release workflow runs) regenerates it.
///
/// Without this registration the failure is silent and dangerous rather than
/// loud: the JS layer's `registerPlugin('TripGuard', { web: ... })` falls
/// back to the WEB MOCK when no native implementation is registered, so a
/// real iPhone would show the mock's fake paired devices and a fake green
/// "ההגנה פעילה" while nothing is actually watching for the end of a trip.
/// A false green light is the one failure mode this whole feature must never
/// have.
///
/// `registerPluginInstance` (not `registerPluginType`): the latter starts
/// with `if autoRegisterPlugins { return }` and is a no-op in a normal build.
/// This is the iOS counterpart to `registerPlugin(TripGuardPlugin.class)` in
/// MainActivity.java on Android.
class MainViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        bridge?.registerPluginInstance(TripGuardPlugin())
    }
}
